spring:
  application:
    name: NMA Service
  datasource:
      url: jdbc:postgresql://localhost:5432/nma_db
      username: postgres
      password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true