integration:
  telegram:
    uri: https://api.telegram.org/bot
    chatid: <YOUR_CHAT_ID>
    botid: <bot_id>
spring:
  application:
    name: integration-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: lohb gdbn gkdk pwfa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: integration-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
